

name: 'Deploy Docker Compose'

on:
  push:
    branches: [ "main" ]
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect ssh and run docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            REPO_URL="https://github.com/Social-Shop/social-shop-backend-deploy.git"
            LOCAL_DIR="repos/social-shop-backend-deploy"
            if [ ! -d "$LOCAL_DIR" ]; 
            then
              git clone "$REPO_URL" "$LOCAL_DIR" && echo "Repository cloned successfully.";
            else
              echo "Repository already exists locally"
            fi
            # Docker compose
            cd "$LOCAL_DIR"
            git checkout -- .
            git pull && echo "Git pull finish";
            chmod u+x scripts/deploy.sh;
            scripts/deploy.sh
